services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./Frontend/Drag and Drop
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
